// Split out of audit.ts so a client component (audit-filters.tsx) can import
// just these labels without pulling audit.ts's `prisma` import (and the
// whole Prisma runtime) into the browser bundle - see tournament-matches.tsx
// for the same fix applied to MATCH_STATUS_FILTER_VALUES.

export const AUDIT_ACTIONS = [
  "match.create",
  "match.update",
  "match.delete",
  "match.score",
  "match.randomize",
  "tournament.create",
  "tournament.update",
  "tournament.delete",
  "tournament.reset",
  "tournament.participant.add",
  "tournament.participant.remove",
  "tournament.participant.seed",
  "tournament.participant.group",
  "tournament.participant.withdraw",
  "tournament.group.create",
  "tournament.group.delete",
  "player.create",
  "player.update",
  "player.delete",
  "player.unlink",
  "player.link",
  "news.create",
  "news.update",
  "news.delete",
  "user.role",
  "photo.upload",
  "photo.delete",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const AUDIT_ACTION_LABEL: Record<AuditAction, string> = {
  "match.create": "Матч створено",
  "match.update": "Матч оновлено",
  "match.delete": "Матч видалено",
  "match.score": "Рахунок збережено",
  "match.randomize": "Рандомайзер",
  "tournament.create": "Турнір створено",
  "tournament.update": "Турнір оновлено",
  "tournament.delete": "Турнір видалено",
  "tournament.reset": "Турнір обнулено",
  "tournament.participant.add": "Учасника додано",
  "tournament.participant.remove": "Учасника видалено",
  "tournament.participant.seed": "Сіяність змінено",
  "tournament.participant.group": "Групу змінено",
  "tournament.participant.withdraw": "Гравця знято з турніру",
  "tournament.group.create": "Групу додано",
  "tournament.group.delete": "Групу видалено",
  "player.create": "Гравця створено",
  "player.update": "Гравця оновлено",
  "player.delete": "Гравця видалено",
  "player.unlink": "Акаунт відв'язано",
  "player.link": "Акаунт прив'язано",
  "news.create": "Новину створено",
  "news.update": "Новину оновлено",
  "news.delete": "Новину видалено",
  "user.role": "Роль змінено",
  "photo.upload": "Фото завантажено",
  "photo.delete": "Фото видалено",
};
