// Split out of audit.ts so a client component (audit-filters.tsx) can import
// just these labels without pulling audit.ts's `prisma` import (and the
// whole Prisma runtime) into the browser bundle - see tournament-matches.tsx
// for the same fix applied to MATCH_STATUS_FILTER_VALUES.

export const AUDIT_ACTIONS = [
  "match.create",
  "match.update",
  "match.delete",
  "match.score",
  "match.randomize",
  "tournament.create",
  "tournament.update",
  "tournament.delete",
  "tournament.reset",
  "tournament.participant.add",
  "tournament.participant.remove",
  "tournament.participant.seed",
  "tournament.participant.group",
  "tournament.participant.withdraw",
  "tournament.group.create",
  "tournament.group.update",
  "tournament.group.delete",
  "tournament.team.create",
  "tournament.team.update",
  "tournament.team.delete",
  "tournament.tie.create",
  "tournament.tie.delete",
  "player.create",
  "player.update",
  "player.delete",
  "player.unlink",
  "player.link",
  "news.create",
  "news.update",
  "news.delete",
  "user.role",
  "user.domains",
  "photo.upload",
  "photo.delete",
  "menu.section.create",
  "menu.section.update",
  "menu.section.delete",
  "menu.section.activate",
  "menu.section.deactivate",
  "menu.item.create",
  "menu.item.update",
  "menu.item.delete",
  "menu.item.activate",
  "menu.item.deactivate",
  "padel.tournament.create",
  "padel.tournament.update",
  "padel.tournament.delete",
  "padel.tournament.reset",
  "padel.tournament.participant.add",
  "padel.tournament.participant.remove",
  "padel.tournament.participant.seed",
  "padel.tournament.participant.group",
  "padel.tournament.participant.withdraw",
  "padel.tournament.group.create",
  "padel.tournament.group.update",
  "padel.tournament.group.delete",
  "padel.match.create",
  "padel.match.update",
  "padel.match.delete",
  "padel.match.score",
  "padel.tournament.team.create",
  "padel.tournament.team.update",
  "padel.tournament.team.delete",
  "padel.tournament.tie.create",
  "padel.tournament.tie.delete",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const AUDIT_ACTION_LABEL: Record<AuditAction, string> = {
  "match.create": "Матч створено",
  "match.update": "Матч оновлено",
  "match.delete": "Матч видалено",
  "match.score": "Рахунок збережено",
  "match.randomize": "Рандомайзер",
  "tournament.create": "Турнір створено",
  "tournament.update": "Турнір оновлено",
  "tournament.delete": "Турнір видалено",
  "tournament.reset": "Турнір обнулено",
  "tournament.participant.add": "Учасника додано",
  "tournament.participant.remove": "Учасника видалено",
  "tournament.participant.seed": "Сіяність змінено",
  "tournament.participant.group": "Групу змінено",
  "tournament.participant.withdraw": "Гравця знято з турніру",
  "tournament.group.create": "Групу додано",
  "tournament.group.update": "Групу оновлено",
  "tournament.group.delete": "Групу видалено",
  "tournament.team.create": "Команду створено",
  "tournament.team.update": "Команду оновлено",
  "tournament.team.delete": "Команду видалено",
  "tournament.tie.create": "Зустріч створено",
  "tournament.tie.delete": "Зустріч видалено",
  "player.create": "Гравця створено",
  "player.update": "Гравця оновлено",
  "player.delete": "Гравця видалено",
  "player.unlink": "Акаунт відв'язано",
  "player.link": "Акаунт прив'язано",
  "news.create": "Новину створено",
  "news.update": "Новину оновлено",
  "news.delete": "Новину видалено",
  "user.role": "Роль змінено",
  "user.domains": "Адмін-розділи змінено",
  "photo.upload": "Фото завантажено",
  "photo.delete": "Фото видалено",
  "menu.section.create": "Секцію меню створено",
  "menu.section.update": "Секцію меню оновлено",
  "menu.section.delete": "Секцію меню видалено",
  "menu.section.activate": "Секцію меню показано",
  "menu.section.deactivate": "Секцію меню приховано",
  "menu.item.create": "Напій створено",
  "menu.item.update": "Напій оновлено",
  "menu.item.delete": "Напій видалено",
  "menu.item.activate": "Напій показано",
  "menu.item.deactivate": "Напій приховано",
  "padel.tournament.create": "Турнір (Падел) створено",
  "padel.tournament.update": "Турнір (Падел) оновлено",
  "padel.tournament.delete": "Турнір (Падел) видалено",
  "padel.tournament.reset": "Турнір (Падел) обнулено",
  "padel.tournament.participant.add": "Учасника (Падел) додано",
  "padel.tournament.participant.remove": "Учасника (Падел) видалено",
  "padel.tournament.participant.seed": "Сіяність (Падел) змінено",
  "padel.tournament.participant.group": "Групу (Падел) змінено",
  "padel.tournament.participant.withdraw": "Гравця знято з турніру (Падел)",
  "padel.tournament.group.create": "Групу (Падел) додано",
  "padel.tournament.group.update": "Групу (Падел) оновлено",
  "padel.tournament.group.delete": "Групу (Падел) видалено",
  "padel.match.create": "Матч (Падел) створено",
  "padel.match.update": "Матч (Падел) оновлено",
  "padel.match.delete": "Матч (Падел) видалено",
  "padel.match.score": "Рахунок (Падел) збережено",
  "padel.tournament.team.create": "Команду (Падел) створено",
  "padel.tournament.team.update": "Команду (Падел) оновлено",
  "padel.tournament.team.delete": "Команду (Падел) видалено",
  "padel.tournament.tie.create": "Зустріч (Падел) створено",
  "padel.tournament.tie.delete": "Зустріч (Падел) видалено",
};
